# Generated by Django 4.1.7 on 2023-11-21 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0003_cust_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_comments',
            name='custcom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.customer'),
        ),
    ]
