# Generated by Django 4.1.7 on 2023-11-21 18:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0004_alter_cust_comments_custcom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cust_comments',
            new_name='cust_comment',
        ),
    ]
